# Plugin de Tutorial para a Gabizinha
# Isto é um comentário! Legal, né?
ideias: # Isto é uma lista de strings (textos)
  - "Fazer uma casa de três andares"
  - "Fazer um templo de adoração a Loritta Morenitta"
  - "Fazer um Burger King"